package com.rtsbuilding.rtsbuilding.server.service.page;
import net.minecraft.creativetab.CreativeTabs; import net.minecraft.entity.player.EntityPlayerMP; import net.minecraft.item.Item; import net.minecraft.item.ItemStack; import net.minecraft.util.NonNullList; import net.minecraft.util.ResourceLocation; import net.minecraftforge.fml.common.registry.ForgeRegistries;
import java.util.*; import java.util.concurrent.*;
public final class RtsPageCreativeTabIndexer {
 private static final ConcurrentMap<String,Set<String>> CACHE=new ConcurrentHashMap<String,Set<String>>(); private static volatile boolean warmNormal,warmOp;
 private RtsPageCreativeTabIndexer(){}
 public static void clearCreativeTabCacheState(){CACHE.clear();warmNormal=false;warmOp=false;}
 static boolean ensureCreativeTabContents(EntityPlayerMP player){boolean op=player!=null&&player.canUseCommand(2,"");if(op?warmOp:warmNormal)return true;synchronized(RtsPageCreativeTabIndexer.class){if(!(op?warmOp:warmNormal)){index(op);if(op)warmOp=true;else warmNormal=true;}}return true;}
 static Set<String> resolveCreativeTabKeys(String itemId,Item item,boolean op){Set<String>s=CACHE.get(key(itemId,op));return s==null?Collections.<String>emptySet():s;}
 static void buildItemTabMapping(Map<String,Long>counts,Map<String,Set<String>>itemTabs,Map<String,Set<String>>modTabs,boolean op){if(counts==null)return;for(String id:counts.keySet()){ResourceLocation rl=parse(id);if(rl==null)continue;Item item=ForgeRegistries.ITEMS.getValue(rl);if(item==null)continue;Set<String>tabs=resolveCreativeTabKeys(id,item,op);if(tabs.isEmpty())continue;Set<String>copy=new HashSet<String>(tabs);itemTabs.put(id,copy);Set<String>mod=modTabs.get(rl.getNamespace());if(mod==null){mod=new HashSet<String>();modTabs.put(rl.getNamespace(),mod);}mod.addAll(copy);}}
 private static void index(boolean op){for(CreativeTabs tab:CreativeTabs.CREATIVE_TAB_ARRAY){if(tab==null)continue;NonNullList<ItemStack> stacks=NonNullList.create();try{tab.displayAllRelevantItems(stacks);}catch(RuntimeException ignored){continue;}String tabKey=tab.getTabLabel();for(ItemStack stack:stacks){if(stack==null||stack.isEmpty())continue;ResourceLocation id=ForgeRegistries.ITEMS.getKey(stack.getItem());if(id==null)continue;String cacheKey=key(id.toString(),op);Set<String>tabs=CACHE.get(cacheKey);if(tabs==null){Set<String>fresh=Collections.newSetFromMap(new ConcurrentHashMap<String,Boolean>());Set<String>prior=CACHE.putIfAbsent(cacheKey,fresh);tabs=prior==null?fresh:prior;}tabs.add(tabKey);}}}
 private static String key(String id,boolean op){return(op?"op|":"normal|")+id;} private static ResourceLocation parse(String id){try{return new ResourceLocation(id);}catch(RuntimeException e){return null;}}
}
