plugins {
    id 'net.neoforged.moddev' version '2.0.140' apply false
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'idea'
    apply plugin: 'maven-publish'

    group = project.property('mod_group_id')
    version = project.property('mod_version')

    repositories {
        mavenCentral()
        maven { url = 'https://maven.blamejared.com' }
        maven { url = 'https://maven.createmod.net' }
        maven { url = 'https://maven.ithundxr.dev/snapshots' }
        maven { url = 'https://api.modrinth.com/maven' }
        maven { url = 'https://jitpack.io' }
    }

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }
}
