package com.rtsbuilding.rtsbuilding.server.workflow.core;

import com.rtsbuilding.rtsbuilding.server.workflow.event.WorkflowEventType;
import com.rtsbuilding.rtsbuilding.server.workflow.model.RtsWorkflowStatus;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.Level;

import javax.annotation.Nullable;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Immutable token representing a single active workflow.
 *
 * <p>This is the <b>primary consumer-facing API</b> for interacting with the workflow system.
 * Instead of manually managing sessions, indices, and entry IDs, callers obtain a token via the engine's factory methods
 * and then call lifecycle methods directly on the token.</p>
 *
 * <p>The token internally holds the player's UUID and the immutable entry ID,
 * so it remains valid even if earlier entries are deleted and indices shift.
 * All methods delegate to the engine that created this token.</p>
 *
 * <h3>Usage</h3>
 * <pre>{@code
 * // Start a workflow and obtain a token
 * var token = engine.startMining(player, 100)
 *         .orElse(null);
 * if (token == null) {
 *     // Workflow queue is full
 *     return;
 * }
 *
 * // During processing
 * for (BlockPos pos : targets) {
 *     if (processBlock(pos)) {
 *         token.markProgress();
 *     } else {
 *         token.recordFailure();
 *     }
 * }
 *
 * // When done
 * token.complete();
 *
 * // Rebuild from other code location:
 * var token2 = engine.from(player, savedEntryId)
 *         .orElse(null);
 * if (token2 != null) {
 *     token2.markProgress();
 * }
 * }</pre>
 *
 * <p>Tokens are <b>not</b> thread-safe — they are designed for single-threaded server tick processing.
 * Create a new token for each distinct workflow.</p>
 */
public record RtsWorkflowToken(
        UUID playerId,
        int entryId,
        ResourceKey<Level> dimension,
        RtsWorkflowEngine engine
) {

    // ──────────────────────────────────────────────────────────────────
    //  Construction (compact constructor — auto-generated by record, validation only)
    // ──────────────────────────────────────────────────────────────────

    public RtsWorkflowToken {
        Objects.requireNonNull(playerId, "playerId");
        Objects.requireNonNull(dimension, "dimension");
        Objects.requireNonNull(engine, "engine");
    }

    // ──────────────────────────────────────────────────────────────────
    //  Identity
    // ──────────────────────────────────────────────────────────────────

    // Accessors auto-generated by record: playerId(), entryId(), dimension()

    /**
     * Returns {@code true} if this token still points to a valid workflow entry
     * (i.e., not yet completed, cancelled, or timed out).
     */
    public boolean isValid() {
        return resolveEntry() != null;
    }

    // ──────────────────────────────────────────────────────────────────
    //  Lifecycle
    // ──────────────────────────────────────────────────────────────────

    /**
     * Mark one unit of progress.
     * Equivalent to {@code updateProgress(1, null)}.
     */
    public void markProgress() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.addCompletedBlocks(1);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Update progress by the specified delta, and optionally report missing items.
     *
     * @param completedDelta Number of units completed since the last update
     * @param missingItems   (nullable) Missing item IDs
     */
    public void updateProgress(int completedDelta, @Nullable List<String> missingItems) {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.addCompletedBlocks(completedDelta);
            entry.addMissingItems(missingItems);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Set the number of completed blocks as an absolute value (for world scan refresh).
     * <p>This is the only "set" method on the token; all other modifications are delta-based.
     * Use with caution — prefer {@link #updateProgress(int, List)} for normal progress.</p>
     */
    public void setCompletedBlocks(int absoluteValue) {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.setCompletedBlocks(absoluteValue);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Set the total block count as an absolute value (use after target collection completes).
     * <p>Use this method when the total block count is only known after the execution phase
     * (e.g., ultimine/area-mine target scanning).</p>
     */
    public void setTotalBlocks(int totalBlocks) {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.setTotalBlocks(totalBlocks);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Record one failure for this workflow.
     */
    public void recordFailure() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.addFailedBlocks(1);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Set a human-readable detail message for this workflow.
     */
    public void setDetailMessage(String message) {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.setDetailMessage(message);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Suspend this workflow (marked as awaiting items).
     */
    public void suspend() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.setSuspended(true);
            entry.setDetailMessage("等待物品...");
            engine.fireEvent(WorkflowEventType.SUSPENDED, playerId, entryId, entry);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Pause this workflow (only stops tick processing for this entry).
     */
    public void pause() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            entry.setPaused(true);
            engine.fireEvent(WorkflowEventType.PAUSED, playerId, entryId, entry);
            engine.notifyPlayer(playerId, dimension);
        }
    }

    /**
     * Unpause this workflow (resume tick processing for this entry).
     *
     * @return {@code true} if the workflow was successfully unpaused
     */
    public boolean unpause() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null && entry.paused()) {
            entry.setPaused(false);
            engine.fireEvent(WorkflowEventType.UNPAUSED, playerId, entryId, entry);
            engine.notifyPlayer(playerId, dimension);
            return true;
        }
        return false;
    }

    /**
     * Returns {@code true} if this workflow entry is paused.
     */
    public boolean isPaused() {
        RtsWorkflowEntry entry = resolveEntry();
        return entry != null && entry.paused();
    }

    /**
     * Resume this workflow if it has been suspended.
     *
     * @return {@code true} if the workflow was successfully resumed
     */
    public boolean resume() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null && entry.suspended()) {
            entry.setSuspended(false);
            entry.setDetailMessage("");
            engine.fireEvent(WorkflowEventType.RESUMED, playerId, entryId, entry);
            engine.notifyPlayer(playerId, dimension);
            return true;
        }
        return false;
    }

    /**
     * Complete this workflow — remove the entry and notify the client.
     *
     * <p>Network notification is handled internally by {@link RtsWorkflowEngine#removeEntry(UUID, ResourceKey, int)},
     * so there is no need to call {@code engine.notifyPlayer()} here.</p>
     */
    public void complete() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            engine.fireEvent(WorkflowEventType.COMPLETED, playerId, entryId, entry);
            engine.removeEntry(playerId, dimension, entryId);
        }
    }

    /**
     * Cancel this workflow — remove the entry without marking as completed.
     *
     * <p>Network notification is handled internally by {@link RtsWorkflowEngine#removeEntry(UUID, ResourceKey, int)},
     * so there is no need to call {@code engine.notifyPlayer()} here.</p>
     */
    public void cancel() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry != null) {
            engine.fireEvent(WorkflowEventType.CANCELLED, playerId, entryId, entry);
            engine.removeEntry(playerId, dimension, entryId);
        }
    }

    // ──────────────────────────────────────────────────────────────────
    //  Queries
    // ──────────────────────────────────────────────────────────────────

    /**
     * Returns an immutable snapshot of this workflow's current progress.
     *
     * @return Workflow status, or {@link RtsWorkflowStatus#idle()} if the entry no longer exists
     */
    public RtsWorkflowStatus getProgress() {
        RtsWorkflowEntry entry = resolveEntry();
        if (entry == null) {
            return RtsWorkflowStatus.idle();
        }
        return entry.snapshot();
    }

    // ──────────────────────────────────────────────────────────────────
    //  Internal Methods
    // ──────────────────────────────────────────────────────────────────

    private RtsWorkflowEntry resolveEntry() {
        return engine.findEntry(playerId, dimension, entryId);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) return true;
        if (!(obj instanceof RtsWorkflowToken other)) return false;
        return this.playerId.equals(other.playerId) && this.entryId == other.entryId;
    }

    @Override
    public int hashCode() {
        return 31 * playerId.hashCode() + entryId;
    }

    @Override
    public String toString() {
        return "RtsWorkflowToken{player=" + playerId + ", entry=" + entryId + "}";
    }
}
