plugins {
    id 'net.neoforged.moddev'
}

base {
    archivesName = "rtsaddon-ae2-${minecraft_version}"
}

neoForge {
    version = project.neo_version
    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
}

dependencies {
    compileOnly project(':rtsbuilding-api')
}
