plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "rtsbuilding-common-${minecraft_version}"
}

neoForge {
    version = project.neo_version
    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
}
