package com.rtsbuilding.rtsbuilding.client.screen.standalone;


import com.mojang.blaze3d.platform.InputConstants;
import com.rtsbuilding.rtsbuilding.Config;
import com.rtsbuilding.rtsbuilding.client.bootstrap.ClientKeyMappings;
import com.rtsbuilding.rtsbuilding.client.controller.ClientRtsController;
import com.rtsbuilding.rtsbuilding.client.network.RtsClientPacketGateway;
import com.rtsbuilding.rtsbuilding.client.pathfinding.RtsClientPathfinding;
import com.rtsbuilding.rtsbuilding.client.record.CraftableEntry;
import com.rtsbuilding.rtsbuilding.client.rendering.builder.BuildGhostBlockStateResolver;
import com.rtsbuilding.rtsbuilding.client.rendering.util.RtsPlacementRayFreeze;
import com.rtsbuilding.rtsbuilding.client.rendering.util.RenderingUtil;
import com.rtsbuilding.rtsbuilding.client.screen.blueprint.*;
import com.rtsbuilding.rtsbuilding.client.screen.craft.RtsCraftQuantityWindowPanel;
import com.rtsbuilding.rtsbuilding.client.screen.culling.RtsCullingClientState;
import com.rtsbuilding.rtsbuilding.client.screen.culling.RtsCullingManager;
import com.rtsbuilding.rtsbuilding.client.screen.culling.RtsCullingPanel;
import com.rtsbuilding.rtsbuilding.client.screen.culling.RtsCullingWorldInput;
import com.rtsbuilding.rtsbuilding.client.screen.funnel.FunnelBufferPanel;
import com.rtsbuilding.rtsbuilding.client.screen.gear.GearMenuPanel;
import com.rtsbuilding.rtsbuilding.client.screen.gear.ThemeSettingsPanel;
import com.rtsbuilding.rtsbuilding.client.screen.guide.GuidePanel;
import com.rtsbuilding.rtsbuilding.client.screen.guide.RtsAiChatPanel;
import com.rtsbuilding.rtsbuilding.uicore.guide.GuideUiContext;
import com.rtsbuilding.rtsbuilding.client.screen.handler.RtsUiScaleFrame;
import com.rtsbuilding.rtsbuilding.client.screen.handler.ScreenCursorPicker;
import com.rtsbuilding.rtsbuilding.client.screen.handler.ScreenShapeController;
import com.rtsbuilding.rtsbuilding.client.screen.handler.StorageLinkDetailHandler;
import com.rtsbuilding.rtsbuilding.client.screen.input.CameraInputHandler;
import com.rtsbuilding.rtsbuilding.client.screen.interaction.InteractionTypes;
import com.rtsbuilding.rtsbuilding.client.screen.layout.BottomPanelLayoutTypes;
import com.rtsbuilding.rtsbuilding.client.screen.mode.BuilderModeWheel;
import com.rtsbuilding.rtsbuilding.client.screen.mode.PlacedBlockRotationGesture;
import com.rtsbuilding.rtsbuilding.client.screen.mode.PlacedBlockRotationHandles;
import com.rtsbuilding.rtsbuilding.client.screen.mode.PlacementStateWheel;
import com.rtsbuilding.rtsbuilding.client.screen.overlay.LeftDockedTooltipRenderer;
import com.rtsbuilding.rtsbuilding.client.screen.overlay.PlayerStatusRenderer;
import com.rtsbuilding.rtsbuilding.client.screen.overlay.RtsScreenOverlayRenderer;
import com.rtsbuilding.rtsbuilding.client.screen.panel.BottomPanel;
import com.rtsbuilding.rtsbuilding.client.screen.panel.RtsFloatingWindowLayer;
import com.rtsbuilding.rtsbuilding.client.screen.quickbuild.BuildShape;
import com.rtsbuilding.rtsbuilding.client.screen.quickbuild.QuickBuildMode;
import com.rtsbuilding.rtsbuilding.client.screen.quickbuild.QuickBuildPanel;
import com.rtsbuilding.rtsbuilding.client.screen.selection.RtsSelectionNudge;
import com.rtsbuilding.rtsbuilding.client.screen.shape.ShapeDataRecords;
import com.rtsbuilding.rtsbuilding.client.screen.shape.ShapeGeometryUtil;
import com.rtsbuilding.rtsbuilding.client.screen.storage.LinkedStoragePanel;
import com.rtsbuilding.rtsbuilding.client.screen.storage.StorageBatchSelectionSession;
import com.rtsbuilding.rtsbuilding.client.screen.topbar.TopBarPanel;
import com.rtsbuilding.rtsbuilding.client.screen.topbar.TopBarTypes;
import com.rtsbuilding.rtsbuilding.client.screen.workflow.RtsBlueprintResumePanel;
import com.rtsbuilding.rtsbuilding.client.screen.workflow.RtsResumePlacementPanel;
import com.rtsbuilding.rtsbuilding.client.screen.workflow.RtsWorkflowPanel;
import com.rtsbuilding.rtsbuilding.client.service.MiningOperationService;
import com.rtsbuilding.rtsbuilding.client.state.RtsScreenUiStateManager;
import com.rtsbuilding.rtsbuilding.client.util.RtsClientUiUtil;
import com.rtsbuilding.rtsbuilding.client.widget.WindowTextBox;
import com.rtsbuilding.rtsbuilding.common.RtsUltimineCollector;
import com.rtsbuilding.rtsbuilding.common.build.BuilderMode;
import com.rtsbuilding.rtsbuilding.common.persist.RtsClientUiStateStore;
import com.rtsbuilding.rtsbuilding.common.shape.model.ShapeFillMode;
import com.rtsbuilding.rtsbuilding.compat.ae2.RtsAe2IconResolver;
import com.rtsbuilding.rtsbuilding.server.plugin.BuiltInRtsPluginCatalog;
import com.rtsbuilding.rtsbuilding.uikit.theme.BottomPanelCraftDockStyle;
import com.rtsbuilding.rtsbuilding.uikit.theme.BottomPanelCraftStyle;
import com.rtsbuilding.rtsbuilding.uikit.theme.RtsMainlineTheme;
import com.rtsbuilding.rtsbuilding.uikit.theme.TooltipStyle;
import com.rtsbuilding.rtsbuilding.client.screen.canvas.MinecraftUiCanvas;
import com.rtsbuilding.rtsbuilding.uicore.geometry.UiRect;
import com.rtsbuilding.rtsbuilding.uikit.canvas.UiChromeRenderer;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.fml.ModList;
import org.lwjgl.glfw.GLFW;

import java.util.List;

import static com.rtsbuilding.rtsbuilding.client.screen.standalone.BuilderScreenConstants.*;

/** BuilderScreen 的组件与交互会话状态；不处理输入优先级或绘制。 */
abstract class BuilderScreenComponentState extends Screen {
    ClientRtsController controller;
    EditBox searchBox;
    EditBox craftSearchBox;
    final FunnelBufferPanel funnelBufferPanel = new FunnelBufferPanel();
    final QuickBuildPanel quickBuildPanel = new QuickBuildPanel();
    final LinkedStoragePanel linkedStoragePanel = new LinkedStoragePanel();
    final StorageBatchSelectionSession storageBatchSelection = new StorageBatchSelectionSession();
    final BlueprintWindowPanel blueprintWindowPanel = new BlueprintWindowPanel();
    final RtsCraftQuantityWindowPanel craftQuantityWindowPanel = new RtsCraftQuantityWindowPanel();
    final BlueprintNameWindowPanel blueprintNameWindowPanel = new BlueprintNameWindowPanel();
    final BlueprintMaterialWindowPanel blueprintMaterialWindowPanel = new BlueprintMaterialWindowPanel();
    final RtsCullingManager cullingManager = RtsCullingClientState.persistentManager();
    final RtsCullingPanel cullingPanel = new RtsCullingPanel(this.cullingManager);
    final TopBarPanel topBarPanel = new TopBarPanel();
    final BottomPanel bottomPanel = new BottomPanel();
    LeftDockedTooltipRenderer leftDockedTooltipRenderer;
    final ScreenShapeController shapeController = new ScreenShapeController();
    final ScreenCursorPicker cursorPicker = new ScreenCursorPicker();
    final CameraInputHandler cameraInput = new CameraInputHandler();
    final BuilderModeWheel modeWheel = new BuilderModeWheel();
    final PlacedBlockRotationHandles rotationHandles = new PlacedBlockRotationHandles();
    final PlacementStateWheel placementStateWheel = new PlacementStateWheel();
    final GuidePanel guidePanel = new GuidePanel();
    final RtsAiChatPanel aiChatPanel = new RtsAiChatPanel();
    final GearMenuPanel gearMenuPanel = new GearMenuPanel();
    final ThemeSettingsPanel themeSettingsPanel = new ThemeSettingsPanel();
    RtsScreenUiStateManager uiStateManager;
    RtsGuiScaleCoordinator guiScaleCoordinator;
    BuilderScreenPointerClickRouter pointerClickRouter;
    BuilderScreenPrimaryActionRouter primaryActionRouter;
    BuilderScreenScrollRouter scrollRouter;
    BuilderScreenKeyPressRouter keyPressRouter;
    RtsScreenOverlayRenderer overlayRenderer;
    PlayerStatusRenderer playerStatusRenderer;
    RtsFloatingWindowLayer floatingWindowLayer;
    StorageLinkDetailHandler storageLinkDetailHandler;
    final RtsWorkflowPanel workflowPanel = new RtsWorkflowPanel();
    final RtsResumePlacementPanel resumePlacementPanel = new RtsResumePlacementPanel();
    final RtsBlueprintResumePanel blueprintResumePanel = new RtsBlueprintResumePanel();
    boolean funnelHotkeyHeld = false;
    BuilderMode modeBeforeFunnelHotkey = BuilderMode.INTERACT;
    boolean funnelHotkeyTemporaryMode = false;
    int funnelMouseHoldButton = -1;
    boolean modeWheelAltWasDown = false;
    int modeWheelConsumedMouseButton = -1;
    int placementStateWheelConsumedMouseButton = -1;
    double placementWheelRestoreMouseX = Double.NaN;
    double placementWheelRestoreMouseY = Double.NaN;
    int lastMouseX = 0;
    int lastMouseY = 0;
    int pendingGuiBindSlot = -1;
    long lastCtrlRightClickTime = 0;
    static final long CTRL_DOUBLE_CLICK_THRESHOLD_MS = 300;
    int rtsFlightToggleCooldownTicks = 0;

    BuilderScreenComponentState(Component title) {
        super(title);
    }
}
