package com.rtsbuilding.rtsbuilding.client.rendering.builder;
import com.rtsbuilding.rtsbuilding.client.screen.shape.ShapeDataRecords;import net.minecraft.client.Minecraft;import net.minecraft.client.renderer.*;import net.minecraft.client.renderer.entity.RenderManager;import net.minecraft.client.renderer.vertex.DefaultVertexFormats;import net.minecraft.util.math.*;import org.lwjgl.opengl.GL11;import java.util.*;
/** 1.12 范围破坏单元格和总包络渲染器。 */
public final class DestructiveGhostRenderer{
 private static final double PAD=.02;private static final BufferBuilder LINES=new BufferBuilder(1024*1024),FILL=new BufferBuilder(1024*1024),NODEPTH=new BufferBuilder(256*1024);private static final WorldVertexBufferUploader UP=new WorldVertexBufferUploader();private DestructiveGhostRenderer(){}
 static void render(ShapeDataRecords.GhostPreview p,BufferBuilder l,BufferBuilder f,float progress,float alpha){render(p,l,f,progress,alpha,null);}static void render(ShapeDataRecords.GhostPreview p,BufferBuilder l,BufferBuilder f,float progress,float alpha,AxisAlignedBB override){render0(p,progress,alpha,true,true,override);}static void render(ShapeDataRecords.GhostPreview p,BufferBuilder l,BufferBuilder f,float progress,float alpha,boolean rf,boolean rl){render0(p,progress,alpha,rf,rl,null);}
 static void renderWireframe(ShapeDataRecords.GhostPreview p,BufferBuilder l,float progress){render0(p,progress,1,false,true,null);}
 private static void render0(ShapeDataRecords.GhostPreview p,float progress,float alpha,boolean doFill,boolean doLines,AxisAlignedBB override){if(p==null||alpha<=0)return;RenderManager m=Minecraft.getMinecraft().getRenderManager();begin(LINES,GL11.GL_LINES,m);begin(FILL,GL11.GL_QUADS,m);begin(NODEPTH,GL11.GL_LINES,m);List<BlockPos>blocks=p.blocks();float lr=lerp(p.readyConfirm()?.95F:1F,.38F,progress),lg=lerp(p.readyConfirm()?.38F:.25F,1F,progress),lb=lerp(.20F,.42F,progress);if(blocks!=null)for(BlockPos q:blocks){double x=q.getX()+.03,y=q.getY()+.03,z=q.getZ()+.03,X=q.getX()+.97,Y=q.getY()+.97,Z=q.getZ()+.97;if(doFill)RenderGlobal.addChainedFilledBoxVertices(FILL,x,y,z,X,Y,Z,lr,lg,lb,.16F*alpha);if(doLines)RenderGlobal.drawBoundingBox(LINES,x,y,z,X,Y,Z,lr,lg,lb,.88F*alpha);}AxisAlignedBB env=override!=null?override:bounds(blocks,p.emptyBlocks());if(env!=null){env=env.grow(PAD);if(doFill)RenderGlobal.addChainedFilledBoxVertices(FILL,env.minX,env.minY,env.minZ,env.maxX,env.maxY,env.maxZ,lerp(1,.3F,progress),lerp(.86F,.95F,progress),lerp(.18F,.36F,progress),.10F*alpha);if(doLines){RenderGlobal.drawBoundingBox(LINES,env.minX,env.minY,env.minZ,env.maxX,env.maxY,env.maxZ,lerp(1,.38F,progress),lerp(.86F,1,progress),lerp(.22F,.42F,progress),.78F*alpha);RenderGlobal.drawBoundingBox(NODEPTH,env.minX,env.minY,env.minZ,env.maxX,env.maxY,env.maxZ,lerp(1,.38F,progress),lerp(.86F,1,progress),lerp(.22F,.42F,progress),.20F*alpha);}}draw(doLines,doFill);}
 private static void begin(BufferBuilder b,int mode,RenderManager m){b.begin(mode,DefaultVertexFormats.POSITION_COLOR);b.setTranslation(-m.viewerPosX,-m.viewerPosY,-m.viewerPosZ);}private static void draw(boolean lines,boolean fill){UltimineGhostRenderer.GlSnapshot gl=UltimineGhostRenderer.GlSnapshot.capture();try{GlStateManager.enableBlend();GlStateManager.disableTexture2D();GlStateManager.depthMask(false);if(lines)UP.draw(LINES);else discard(LINES);if(fill)UP.draw(FILL);else discard(FILL);if(lines){GlStateManager.disableDepth();UP.draw(NODEPTH);GlStateManager.enableDepth();}else discard(NODEPTH);}finally{LINES.setTranslation(0,0,0);FILL.setTranslation(0,0,0);NODEPTH.setTranslation(0,0,0);gl.restore();}}
 private static void discard(BufferBuilder b){b.finishDrawing();b.reset();}private static AxisAlignedBB bounds(List<BlockPos>a,List<BlockPos>b){int minX=Integer.MAX_VALUE,minY=minX,minZ=minX,maxX=Integer.MIN_VALUE,maxY=maxX,maxZ=maxX;boolean any=false;for(List<BlockPos>l:Arrays.asList(a,b))if(l!=null)for(BlockPos p:l){any=true;minX=Math.min(minX,p.getX());minY=Math.min(minY,p.getY());minZ=Math.min(minZ,p.getZ());maxX=Math.max(maxX,p.getX()+1);maxY=Math.max(maxY,p.getY()+1);maxZ=Math.max(maxZ,p.getZ()+1);}return any?new AxisAlignedBB(minX,minY,minZ,maxX,maxY,maxZ):null;}private static float lerp(float a,float b,float t){t=Math.max(0,Math.min(1,t));return a+(b-a)*t;}
}
