package com.rtsbuilding.rtsbuilding.core.network;

public enum ActionType {
    SET_MODE, TOGGLE_CAMERA, SET_FUNNEL, SET_AUTO_STORE, SET_BD_NETWORK,
    LINK_STORAGE, UNLINK_STORAGE, UPDATE_LINKED_STORAGE, LINKED_QUICK_MOVE,
    LINKED_PICKUP, IMPORT_MENU_SLOT, FUNNEL_TARGET, FILL_INVENTORY,
    CLOSE_REMOTE_MENU, STORE_HOTBAR_SLOT, SET_QUICK_SLOT, SET_GUI_BINDING,
    RETURN_CARRIED, REQUEST_PAGE, OPEN_GUI_BINDING,
    CRAFT_RECIPE, CRAFT_REFILL, JEI_TRANSFER, REQUEST_CRAFTABLES,
    OPEN_CRAFT_TERMINAL,
    SET_PROGRESSION, SET_HOME, REQUEST_PROGRESSION,
    QUEST_DETECT, BEGIN_HOME_SELECTION,
    INSTALL_PLUGIN, UNINSTALL_PLUGIN, REQUEST_PLUGINS,
    PATHFIND,
    PLACE_BLOCK, PLACE_BATCH, PLACE_FLUID, ROTATE_BLOCK, SUBMIT_PENDING,
    RESUME_PLACEMENT, MINE_BLOCK, AREA_MINE, AREA_DESTROY, ULTIMINE, BREAK,
    INTERACT_BLOCK, STORE_FLUID, QUICK_DROP, UNDO,
    BLUEPRINT_PLACE, BLUEPRINT_SCAN, BLUEPRINT_SCAN_RESUME,
    PAUSE_WORKFLOW, DELETE_WORKFLOW,
}
